// <auto-generated />
using System;
using HomeManagement.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HomeManagement.Infrastructure.Migrations;

[DbContext(typeof(HomeManagementDbContext))]
[Migration("20260821143039_AppSettingsTypedValues")]
partial class _20260821143039_AppSettingsTypedValues
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "11.0.0-preview.7.26381.103");

        modelBuilder.Entity("HomeManagement.Shared.AppSetting", b =>
            {
                b.Property<string>("Name")
                    .HasMaxLength(100)
                    .HasColumnType("TEXT");

                b.Property<string>("Value")
                    .IsRequired()
                    .HasMaxLength(2000)
                    .HasColumnType("TEXT");

                b.Property<int>("ValueType")
                    .HasColumnType("INTEGER");

                b.HasKey("Name");

                b.ToTable("AppSettings");
            });

        modelBuilder.Entity("HomeManagement.Shared.Device", b =>
            {
                b.Property<string>("Name")
                    .HasMaxLength(100)
                    .HasColumnType("TEXT");

                b.Property<string>("Address")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("TEXT");

                b.Property<string>("Description")
                    .HasColumnType("TEXT");

                b.HasKey("Name");

                b.ToTable("Devices");
            });

        modelBuilder.Entity("HomeManagement.Shared.Workflow", b =>
            {
                b.Property<string>("Name")
                    .HasMaxLength(100)
                    .HasColumnType("TEXT");

                b.Property<int>("ConditionOperator")
                    .HasColumnType("INTEGER");

                b.Property<string>("Description")
                    .HasMaxLength(400)
                    .HasColumnType("TEXT");

                b.Property<bool>("IsEnabled")
                    .HasColumnType("INTEGER");

                b.Property<bool?>("LastConditionMatched")
                    .HasColumnType("INTEGER");

                b.Property<DateTimeOffset?>("LastTriggeredAtUtc")
                    .HasColumnType("TEXT");

                b.HasKey("Name");

                b.ToTable("Workflows");
            });

        modelBuilder.Entity("HomeManagement.Shared.Device", b =>
            {
                b.OwnsMany("HomeManagement.Shared.DeviceAction", "Actions", b1 =>
                    {
                        b1.Property<int>("Id")
                            .ValueGeneratedOnAdd()
                            .HasColumnType("INTEGER");

                        b1.Property<string>("Action")
                            .IsRequired()
                            .HasMaxLength(50)
                            .HasColumnType("TEXT");

                        b1.Property<string>("Command")
                            .IsRequired()
                            .HasColumnType("TEXT");

                        b1.Property<string>("CommandArgs")
                            .HasColumnType("TEXT");

                        b1.Property<int>("CommandType")
                            .HasColumnType("INTEGER");

                        b1.Property<string>("DeviceName")
                            .IsRequired()
                            .HasColumnType("TEXT");

                        b1.HasKey("Id");

                        b1.HasIndex("DeviceName");

                        b1.ToTable("DeviceActions");

                        b1.WithOwner()
                            .HasForeignKey("DeviceName");
                    });

                b.OwnsMany("HomeManagement.Shared.DeviceConfiguration", "Configurations", b1 =>
                    {
                        b1.Property<int>("Id")
                            .ValueGeneratedOnAdd()
                            .HasColumnType("INTEGER");

                        b1.Property<string>("DeviceName")
                            .IsRequired()
                            .HasColumnType("TEXT");

                        b1.Property<string>("Name")
                            .IsRequired()
                            .HasMaxLength(50)
                            .HasColumnType("TEXT");

                        b1.Property<string>("Value")
                            .IsRequired()
                            .HasColumnType("TEXT");

                        b1.HasKey("Id");

                        b1.HasIndex("DeviceName");

                        b1.ToTable("DeviceConfigurations");

                        b1.WithOwner()
                            .HasForeignKey("DeviceName");
                    });

                b.Navigation("Actions");

                b.Navigation("Configurations");
            });

        modelBuilder.Entity("HomeManagement.Shared.Workflow", b =>
            {
                b.OwnsMany("HomeManagement.Shared.WorkflowStep", "Steps", b1 =>
                    {
                        b1.Property<int>("Id")
                            .ValueGeneratedOnAdd()
                            .HasColumnType("INTEGER");

                        b1.Property<string>("ActionName")
                            .HasMaxLength(100)
                            .HasColumnType("TEXT");

                        b1.Property<int?>("DelaySeconds")
                            .HasColumnType("INTEGER");

                        b1.Property<string>("DeviceName")
                            .HasMaxLength(100)
                            .HasColumnType("TEXT");

                        b1.Property<string>("NotifyMessageTemplate")
                            .HasMaxLength(2000)
                            .HasColumnType("TEXT");

                        b1.Property<string>("NotifyTitle")
                            .HasMaxLength(200)
                            .HasColumnType("TEXT");

                        b1.Property<int>("StepType")
                            .HasColumnType("INTEGER");

                        b1.Property<string>("WorkflowName")
                            .IsRequired()
                            .HasColumnType("TEXT");

                        b1.HasKey("Id");

                        b1.HasIndex("WorkflowName");

                        b1.ToTable("WorkflowSteps");

                        b1.WithOwner()
                            .HasForeignKey("WorkflowName");
                    });

                b.OwnsMany("HomeManagement.Shared.WorkflowTriggerCondition", "TriggerConditions", b1 =>
                    {
                        b1.Property<int>("Id")
                            .ValueGeneratedOnAdd()
                            .HasColumnType("INTEGER");

                        b1.Property<bool?>("LastConditionMatched")
                            .HasColumnType("INTEGER");

                        b1.Property<DateTime?>("LastTriggerDateLocal")
                            .HasColumnType("TEXT");

                        b1.Property<DateTimeOffset?>("LastTriggeredAtUtc")
                            .HasColumnType("TEXT");

                        b1.Property<DateTimeOffset?>("ScheduledAt")
                            .HasColumnType("TEXT");

                        b1.Property<string>("TriggerDeviceName")
                            .HasMaxLength(100)
                            .HasColumnType("TEXT");

                        b1.Property<string>("TriggerExpectedValue")
                            .HasMaxLength(500)
                            .HasColumnType("TEXT");

                        b1.Property<int?>("TriggerOperator")
                            .HasColumnType("INTEGER");

                        b1.Property<string>("TriggerPropertyPath")
                            .HasMaxLength(200)
                            .HasColumnType("TEXT");

                        b1.Property<string>("TriggerSourceActionName")
                            .HasMaxLength(100)
                            .HasColumnType("TEXT");

                        b1.Property<int>("TriggerType")
                            .HasColumnType("INTEGER");

                        b1.Property<int?>("TriggerValueType")
                            .HasColumnType("INTEGER");

                        b1.Property<string>("WorkflowName")
                            .IsRequired()
                            .HasColumnType("TEXT");

                        b1.HasKey("Id");

                        b1.HasIndex("WorkflowName");

                        b1.ToTable("WorkflowTriggerConditions");

                        b1.WithOwner()
                            .HasForeignKey("WorkflowName");
                    });

                b.Navigation("Steps");

                b.Navigation("TriggerConditions");
            });
#pragma warning restore 612, 618
    }
}
