// <auto-generated />
using HomeManagement.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HomeManagement.Infrastructure.Migrations
{
    [DbContext(typeof(HomeManagementDbContext))]
    [Migration("20260705132047_DeviceAddress")]
    partial class DeviceAddress
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("HomeManagement.Shared.Device", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.ToTable("Devices", (string)null);
                });

            modelBuilder.Entity("HomeManagement.Shared.Device", b =>
                {
                    b.OwnsMany("HomeManagement.Shared.DeviceAction", "Actions", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Action")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Command")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("CommandArgs")
                                .HasColumnType("TEXT");

                            b1.Property<int>("CommandType")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("DeviceName")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("DeviceName");

                            b1.ToTable("DeviceActions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("DeviceName");
                        });

                    b.Navigation("Actions");
                });
#pragma warning restore 612, 618
        }
    }
}
