// <auto-generated />
using HomeManagement;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HomeManagement.Migrations
{
    [DbContext(typeof(HomeManagementDbContext))]
    partial class HomeManagementDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("HomeManagement.Device", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("UptimeSeconds")
                        .HasColumnType("INTEGER");

                    b.HasKey("Name");

                    b.ToTable("Devices", (string)null);
                });

            modelBuilder.Entity("HomeManagement.Device", b =>
                {
                    b.OwnsMany("HomeManagement.DeviceAction", "Actions", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Action")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Command")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("DeviceName")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("DeviceName");

                            b1.ToTable("DeviceActions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("DeviceName");
                        });

                    b.Navigation("Actions");
                });
#pragma warning restore 612, 618
        }
    }
}
